---
dist: xenial
language: generic

before_install:
  - openssl aes-256-cbc -K $encrypted_bb96840a4ac0_key -iv $encrypted_bb96840a4ac0_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xf secrets.tar

before_script:
  - bash scripts/prepare.sh

script:
  - bash scripts/run.sh

after_success:
  - bash scripts/push.sh
